[firebase]
apiKey = "your_api_key"
authDomain = "your_project.firebaseapp.com"
projectId = "your_project_id"
storageBucket = "your_project.appspot.com"
messagingSenderId = "..."
appId = "..."

[email]
sender = "sidinregina@gmail.com"
password = "gmdnghznftupisyx"
